/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tugas8;

/**
 *
 * @author soery
 */
public class Kalkulator extends javax.swing.JFrame {

    String number;
    double hasil, bil1, bil2;
    int input;
    
    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
        number = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        fieldHasil = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        butTujuh = new javax.swing.JButton();
        butEmpat = new javax.swing.JButton();
        butLima = new javax.swing.JButton();
        butSembilan = new javax.swing.JButton();
        butDelapan = new javax.swing.JButton();
        butEnam = new javax.swing.JButton();
        butTiga = new javax.swing.JButton();
        butDua = new javax.swing.JButton();
        butSatu = new javax.swing.JButton();
        titik = new javax.swing.JButton();
        butNol = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        pertambahan = new javax.swing.JButton();
        perkalian = new javax.swing.JButton();
        pembagian = new javax.swing.JButton();
        pengurangan = new javax.swing.JButton();
        modulo = new javax.swing.JButton();
        samaDengan = new javax.swing.JButton();
        B = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        fieldHasil.setText("0");
        fieldHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHasilActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kalkulator Cashoy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(fieldHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(fieldHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        butTujuh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butTujuh.setText("7");
        butTujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTujuhActionPerformed(evt);
            }
        });

        butEmpat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butEmpat.setText("4");
        butEmpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEmpatActionPerformed(evt);
            }
        });

        butLima.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butLima.setText("5");
        butLima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLimaActionPerformed(evt);
            }
        });

        butSembilan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butSembilan.setText("9");
        butSembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSembilanActionPerformed(evt);
            }
        });

        butDelapan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butDelapan.setText("8");
        butDelapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDelapanActionPerformed(evt);
            }
        });

        butEnam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butEnam.setText("6");
        butEnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEnamActionPerformed(evt);
            }
        });

        butTiga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butTiga.setText("3");
        butTiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTigaActionPerformed(evt);
            }
        });

        butDua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butDua.setText("2");
        butDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDuaActionPerformed(evt);
            }
        });

        butSatu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butSatu.setText("1");
        butSatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSatuActionPerformed(evt);
            }
        });

        titik.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titik.setText(".");
        titik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titikActionPerformed(evt);
            }
        });

        butNol.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butNol.setText("0");
        butNol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNolActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(butTujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butDelapan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butSembilan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(butEmpat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butLima, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butEnam, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(butSatu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butDua, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butTiga, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(titik, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butNol, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butTujuh)
                    .addComponent(butDelapan)
                    .addComponent(butSembilan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butEmpat)
                    .addComponent(butLima)
                    .addComponent(butEnam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butSatu)
                    .addComponent(butDua)
                    .addComponent(butTiga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titik)
                    .addComponent(butNol)
                    .addComponent(clear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        pertambahan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pertambahan.setText("+");
        pertambahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pertambahanActionPerformed(evt);
            }
        });

        perkalian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        perkalian.setText("*");
        perkalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perkalianActionPerformed(evt);
            }
        });

        pembagian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pembagian.setText("/");
        pembagian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembagianActionPerformed(evt);
            }
        });

        pengurangan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pengurangan.setText("-");
        pengurangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penguranganActionPerformed(evt);
            }
        });

        modulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        modulo.setText("%");
        modulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduloActionPerformed(evt);
            }
        });

        samaDengan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        samaDengan.setText("=");
        samaDengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samaDenganActionPerformed(evt);
            }
        });

        B.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        B.setText("Main Menu");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(pertambahan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pengurangan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(perkalian, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pembagian, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(samaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pertambahan)
                    .addComponent(pengurangan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perkalian)
                    .addComponent(pembagian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(samaDengan)
                    .addComponent(modulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butTujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTujuhActionPerformed
        number += "7";
        fieldHasil.setText(number);
    }//GEN-LAST:event_butTujuhActionPerformed

    private void butEmpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEmpatActionPerformed
        number += "4";
        fieldHasil.setText(number);
    }//GEN-LAST:event_butEmpatActionPerformed

    private void butLimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLimaActionPerformed
        number += "5";
        fieldHasil.setText(number);
    }//GEN-LAST:event_butLimaActionPerformed

    private void butSembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSembilanActionPerformed
        number += "9";
        fieldHasil.setText(number);
    }//GEN-LAST:event_butSembilanActionPerformed

    private void butDelapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDelapanActionPerformed
        number += "8";
        fieldHasil.setText(number);
    }//GEN-LAST:event_butDelapanActionPerformed

    private void butEnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEnamActionPerformed
        number += "6";
        fieldHasil.setText(number);
    }//GEN-LAST:event_butEnamActionPerformed

    private void butTigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTigaActionPerformed
        number += "3";
        fieldHasil.setText(number);
    }//GEN-LAST:event_butTigaActionPerformed

    private void butDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDuaActionPerformed
        number += "2";
        fieldHasil.setText(number);
    }//GEN-LAST:event_butDuaActionPerformed

    private void butSatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSatuActionPerformed
        number += "1";
        fieldHasil.setText(number);
    }//GEN-LAST:event_butSatuActionPerformed

    private void titikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titikActionPerformed
        number += ".";
        fieldHasil.setText(number);
    }//GEN-LAST:event_titikActionPerformed

    private void butNolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNolActionPerformed
        number += "0";
        fieldHasil.setText(number);
    }//GEN-LAST:event_butNolActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        bil1 = 0.0;
        bil2 = 0.0;
        hasil = 0.0;
        number = "";
        fieldHasil.setText("0");
        
    }//GEN-LAST:event_clearActionPerformed

    private void pertambahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pertambahanActionPerformed
        bil1 = Double.parseDouble(number);
        fieldHasil.setText("+");
        number = "";
        input = 1;
    }//GEN-LAST:event_pertambahanActionPerformed

    private void perkalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perkalianActionPerformed
        bil1 = Double.parseDouble(number);
        fieldHasil.setText("x");
        number = "";
        input = 3;
    }//GEN-LAST:event_perkalianActionPerformed

    private void pembagianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembagianActionPerformed
        bil1 = Double.parseDouble(number);
        fieldHasil.setText("/");
        number = "";
        input = 4;
    }//GEN-LAST:event_pembagianActionPerformed

    private void penguranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penguranganActionPerformed
        bil1 = Double.parseDouble(number);
        fieldHasil.setText("-");
        number = "";
        input = 2;
    }//GEN-LAST:event_penguranganActionPerformed

    private void moduloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduloActionPerformed
        bil1 = Double.parseDouble(number);
        fieldHasil.setText("%");
        number = "";
        input = 5;
    }//GEN-LAST:event_moduloActionPerformed

    private void samaDenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samaDenganActionPerformed
        switch (input){
            case 1:
                bil2 = Double.parseDouble(number);
                hasil = bil1+bil2;
                number = Double.toString(hasil);
                fieldHasil.setText(number);
                break;
            case 2:
                bil2 = Double.parseDouble(number);
                hasil = bil1-bil2;
                number = Double.toString(hasil);
                fieldHasil.setText(number);
                break;
            case 3:
                bil2 = Double.parseDouble(number);
                hasil = bil1*bil2;
                number = Double.toString(hasil);
                fieldHasil.setText(number);
                break;
            case 4:
                bil2 = Double.parseDouble(number);
                hasil = bil1/bil2;
                number = Double.toString(hasil);
                fieldHasil.setText(number);
                break;
            case 5:
                bil2 = Double.parseDouble(number);
                hasil = bil1%bil2;
                number = Double.toString(hasil);
                fieldHasil.setText(number);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_samaDenganActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        new MainMenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_BActionPerformed

    private void fieldHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B;
    private javax.swing.JButton butDelapan;
    private javax.swing.JButton butDua;
    private javax.swing.JButton butEmpat;
    private javax.swing.JButton butEnam;
    private javax.swing.JButton butLima;
    private javax.swing.JButton butNol;
    private javax.swing.JButton butSatu;
    private javax.swing.JButton butSembilan;
    private javax.swing.JButton butTiga;
    private javax.swing.JButton butTujuh;
    private javax.swing.JButton clear;
    private javax.swing.JTextField fieldHasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton modulo;
    private javax.swing.JButton pembagian;
    private javax.swing.JButton pengurangan;
    private javax.swing.JButton perkalian;
    private javax.swing.JButton pertambahan;
    private javax.swing.JButton samaDengan;
    private javax.swing.JButton titik;
    // End of variables declaration//GEN-END:variables
}
